import { DexDetails } from "@favware/graphql-pokemon/generated/ts/graphql-pokemon";
import { SectionListData } from "react-native";
import { mapPokemonToItem } from "../../mappers/pokemon";
import { Item } from "../List/SectionList";

export interface PokemonGeneration {
  title: string;
  data: Pokemon[];
}

export interface Pokemon {
  readonly num: number;
  readonly species: string;
  readonly types: string[];
  readonly baseSpecies?: string;
}

export const getPokemonData = (
  pokemon: DexDetails,
  openPokemonScreen: (number: number) => void
): SectionListData<Item>[] => {
  return [
    {
      title: "General",
      data: [
        { field: "Number", value: pokemon.num },
        { field: "Name", value: pokemon.species },
        { field: "Color", value: pokemon.color },
        { field: "Height", value: `${pokemon.height} meters` },
        { field: "Weight", value: `${pokemon.weight} Kg.` },
        { field: "Types", value: pokemon.types.join(", ") },
      ],
    },
    {
      title: "Stats",
      data: [
        {
          field: "HP",
          value: pokemon.baseStats.hp,
        },
        { field: "Attack", value: pokemon.baseStats.attack },
        {
          field: "Defense",
          value: pokemon.baseStats.defense,
        },

        {
          field: "Speed",
          value: pokemon.baseStats.speed,
        },
        {
          field: "Special Attack",
          value: pokemon.baseStats.specialattack,
        },
        {
          field: "Special Defense",
          value: pokemon.baseStats.specialdefense,
        },
        {
          field: "Total",
          value: pokemon.baseStatsTotal,
        },
      ],
    },
    {
      title: "Abilities",
      data: [
        { field: "First", value: pokemon.abilities.first },
        {
          field: "Second",
          value: pokemon.abilities.second as string,
        },
        {
          field: "Special",
          value: pokemon.abilities.special as string,
        },
        {
          field: "Hidden",
          value: pokemon.abilities.hidden as string,
        },
      ],
    },
    {
      title: "Egg Groups",
      data:
        pokemon.eggGroups?.map((egg) => ({
          value: egg,
        })) || [],
    },
    {
      title: "Pre-Evolutions",
      data: getPreEvolutions(pokemon, openPokemonScreen),
    },
    {
      title: "Evolutions",
      data: getEvolutions(pokemon, openPokemonScreen),
    },
  ];
};

const getEvolutions = (pokemon: DexDetails, changePokemon: any): Item[] =>
  pokemon.evolutions?.map((evolution) =>
    mapPokemonToItem(evolution, changePokemon)
  ) || [];

const getPreEvolutions = (pokemon: DexDetails, changePokemon: any): Item[] =>
  pokemon.preevolutions?.map((preevoluton) =>
    mapPokemonToItem(preevoluton, changePokemon)
  ) || [];

export const pokemonGenerations: PokemonGeneration[] = [
  {
    title: "Generation 1",
    data: [
      { num: 1, species: "Bulbasaur", types: ["Grass", "Poison"] },
      { num: 2, species: "Ivysaur", types: ["Grass", "Poison"] },
      { num: 3, species: "Venusaur", types: ["Grass", "Poison"] },
      { num: 4, species: "Charmander", types: ["Fire"] },
      { num: 5, species: "Charmeleon", types: ["Fire"] },
      { num: 6, species: "Charizard", types: ["Fire", "Flying"] },
      { num: 7, species: "Squirtle", types: ["Water"] },
      { num: 8, species: "Wartortle", types: ["Water"] },
      { num: 9, species: "Blastoise", types: ["Water"] },
      { num: 10, species: "Caterpie", types: ["Bug"] },
      { num: 11, species: "Metapod", types: ["Bug"] },
      { num: 12, species: "Butterfree", types: ["Bug", "Flying"] },
      { num: 13, species: "Weedle", types: ["Bug", "Poison"] },
      { num: 14, species: "Kakuna", types: ["Bug", "Poison"] },
      { num: 15, species: "Beedrill", types: ["Bug", "Poison"] },
      { num: 16, species: "Pidgey", types: ["Normal", "Flying"] },
      { num: 17, species: "Pidgeotto", types: ["Normal", "Flying"] },
      { num: 18, species: "Pidgeot", types: ["Normal", "Flying"] },
      { num: 19, species: "Rattata", types: ["Normal"] },
      { num: 20, species: "Raticate", types: ["Normal"] },
      { num: 21, species: "Spearow", types: ["Normal", "Flying"] },
      { num: 22, species: "Fearow", types: ["Normal", "Flying"] },
      { num: 23, species: "Ekans", types: ["Poison"] },
      { num: 24, species: "Arbok", types: ["Poison"] },
      { num: 25, species: "Pikachu", types: ["Electric"] },
      { num: 26, species: "Raichu", types: ["Electric"] },
      { num: 27, species: "Sandshrew", types: ["Ground"] },
      { num: 28, species: "Sandslash", types: ["Ground"] },
      { num: 29, species: "Nidoran♀", types: ["Poison"] },
      { num: 30, species: "Nidorina", types: ["Poison"] },
      { num: 31, species: "Nidoqueen", types: ["Poison", "Ground"] },
      { num: 32, species: "Nidoran♂", types: ["Poison"] },
      { num: 33, species: "Nidorino", types: ["Poison"] },
      { num: 34, species: "Nidoking", types: ["Poison", "Ground"] },
      { num: 35, species: "Clefairy", types: ["Fairy"] },
      { num: 36, species: "Clefable", types: ["Fairy"] },
      { num: 37, species: "Vulpix", types: ["Fire"] },
      { num: 38, species: "Ninetales", types: ["Fire"] },
      { num: 39, species: "Jigglypuff", types: ["Normal", "Fairy"] },
      { num: 40, species: "Wigglytuff", types: ["Normal", "Fairy"] },
      { num: 41, species: "Zubat", types: ["Poison", "Flying"] },
      { num: 42, species: "Golbat", types: ["Poison", "Flying"] },
      { num: 43, species: "Oddish", types: ["Grass", "Poison"] },
      { num: 44, species: "Gloom", types: ["Grass", "Poison"] },
      { num: 45, species: "Vileplume", types: ["Grass", "Poison"] },
      { num: 46, species: "Paras", types: ["Bug", "Grass"] },
      { num: 47, species: "Parasect", types: ["Bug", "Grass"] },
      { num: 48, species: "Venonat", types: ["Bug", "Poison"] },
      { num: 49, species: "Venomoth", types: ["Bug", "Poison"] },
      { num: 50, species: "Diglett", types: ["Ground"] },
      { num: 51, species: "Dugtrio", types: ["Ground"] },
      { num: 52, species: "Meowth", types: ["Normal"] },
      { num: 53, species: "Persian", types: ["Normal"] },
      { num: 54, species: "Psyduck", types: ["Water"] },
      { num: 55, species: "Golduck", types: ["Water"] },
      { num: 56, species: "Mankey", types: ["Fighting"] },
      { num: 57, species: "Primeape", types: ["Fighting"] },
      { num: 58, species: "Growlithe", types: ["Fire"] },
      { num: 59, species: "Arcanine", types: ["Fire"] },
      { num: 60, species: "Poliwag", types: ["Water"] },
      { num: 61, species: "Poliwhirl", types: ["Water"] },
      { num: 62, species: "Poliwrath", types: ["Water", "Fighting"] },
      { num: 63, species: "Abra", types: ["Psychic"] },
      { num: 64, species: "Kadabra", types: ["Psychic"] },
      { num: 65, species: "Alakazam", types: ["Psychic"] },
      { num: 66, species: "Machop", types: ["Fighting"] },
      { num: 67, species: "Machoke", types: ["Fighting"] },
      { num: 68, species: "Machamp", types: ["Fighting"] },
      { num: 69, species: "Bellsprout", types: ["Grass", "Poison"] },
      { num: 70, species: "Weepinbell", types: ["Grass", "Poison"] },
      { num: 71, species: "Victreebel", types: ["Grass", "Poison"] },
      { num: 72, species: "Tentacool", types: ["Water", "Poison"] },
      { num: 73, species: "Tentacruel", types: ["Water", "Poison"] },
      { num: 74, species: "Geodude", types: ["Rock", "Ground"] },
      { num: 75, species: "Graveler", types: ["Rock", "Ground"] },
      { num: 76, species: "Golem", types: ["Rock", "Ground"] },
      { num: 77, species: "Ponyta", types: ["Fire"] },
      { num: 78, species: "Rapidash", types: ["Fire"] },
      { num: 79, species: "Slowpoke", types: ["Water", "Psychic"] },
      { num: 80, species: "Slowbro", types: ["Water", "Psychic"] },
      { num: 81, species: "Magnemite", types: ["Electric", "Steel"] },
      { num: 82, species: "Magneton", types: ["Electric", "Steel"] },
      { num: 83, species: "Farfetch'd", types: ["Normal", "Flying"] },
      { num: 84, species: "Doduo", types: ["Normal", "Flying"] },
      { num: 85, species: "Dodrio", types: ["Normal", "Flying"] },
      { num: 86, species: "Seel", types: ["Water"] },
      { num: 87, species: "Dewgong", types: ["Water", "Ice"] },
      { num: 88, species: "Grimer", types: ["Poison"] },
      { num: 89, species: "Muk", types: ["Poison"] },
      { num: 90, species: "Shellder", types: ["Water"] },
      { num: 91, species: "Cloyster", types: ["Water", "Ice"] },
      { num: 92, species: "Gastly", types: ["Ghost", "Poison"] },
      { num: 93, species: "Haunter", types: ["Ghost", "Poison"] },
      { num: 94, species: "Gengar", types: ["Ghost", "Poison"] },
      { num: 95, species: "Onix", types: ["Rock", "Ground"] },
      { num: 96, species: "Drowzee", types: ["Psychic"] },
      { num: 97, species: "Hypno", types: ["Psychic"] },
      { num: 98, species: "Krabby", types: ["Water"] },
      { num: 99, species: "Kingler", types: ["Water"] },
      { num: 100, species: "Voltorb", types: ["Electric"] },
      { num: 101, species: "Electrode", types: ["Electric"] },
      { num: 102, species: "Exeggcute", types: ["Grass", "Psychic"] },
      { num: 103, species: "Exeggutor", types: ["Grass", "Psychic"] },
      { num: 104, species: "Cubone", types: ["Ground"] },
      { num: 105, species: "Marowak", types: ["Ground"] },
      { num: 106, species: "Hitmonlee", types: ["Fighting"] },
      { num: 107, species: "Hitmonchan", types: ["Fighting"] },
      { num: 108, species: "Lickitung", types: ["Normal"] },
      { num: 109, species: "Koffing", types: ["Poison"] },
      { num: 110, species: "Weezing", types: ["Poison"] },
      { num: 111, species: "Rhyhorn", types: ["Ground", "Rock"] },
      { num: 112, species: "Rhydon", types: ["Ground", "Rock"] },
      { num: 113, species: "Chansey", types: ["Normal"] },
      { num: 114, species: "Tangela", types: ["Grass"] },
      { num: 115, species: "Kangaskhan", types: ["Normal"] },
      { num: 116, species: "Horsea", types: ["Water"] },
      { num: 117, species: "Seadra", types: ["Water"] },
      { num: 118, species: "Goldeen", types: ["Water"] },
      { num: 119, species: "Seaking", types: ["Water"] },
      { num: 120, species: "Staryu", types: ["Water"] },
      { num: 121, species: "Starmie", types: ["Water", "Psychic"] },
      { num: 122, species: "Mr. Mime", types: ["Psychic", "Fairy"] },
      { num: 123, species: "Scyther", types: ["Bug", "Flying"] },
      { num: 124, species: "Jynx", types: ["Ice", "Psychic"] },
      { num: 125, species: "Electabuzz", types: ["Electric"] },
      { num: 126, species: "Magmar", types: ["Fire"] },
      { num: 127, species: "Pinsir", types: ["Bug"] },
      { num: 128, species: "Tauros", types: ["Normal"] },
      { num: 129, species: "Magikarp", types: ["Water"] },
      { num: 130, species: "Gyarados", types: ["Water", "Flying"] },
      { num: 131, species: "Lapras", types: ["Water", "Ice"] },
      { num: 132, species: "Ditto", types: ["Normal"] },
      { num: 133, species: "Eevee", types: ["Normal"] },
      { num: 134, species: "Vaporeon", types: ["Water"] },
      { num: 135, species: "Jolteon", types: ["Electric"] },
      { num: 136, species: "Flareon", types: ["Fire"] },
      { num: 137, species: "Porygon", types: ["Normal"] },
      { num: 138, species: "Omanyte", types: ["Rock", "Water"] },
      { num: 139, species: "Omastar", types: ["Rock", "Water"] },
      { num: 140, species: "Kabuto", types: ["Rock", "Water"] },
      { num: 141, species: "Kabutops", types: ["Rock", "Water"] },
      { num: 142, species: "Aerodactyl", types: ["Rock", "Flying"] },
      { num: 143, species: "Snorlax", types: ["Normal"] },
      { num: 144, species: "Articuno", types: ["Ice", "Flying"] },
      { num: 145, species: "Zapdos", types: ["Electric", "Flying"] },
      { num: 146, species: "Moltres", types: ["Fire", "Flying"] },
      { num: 147, species: "Dratini", types: ["Dragon"] },
      { num: 148, species: "Dragonair", types: ["Dragon"] },
      { num: 149, species: "Dragonite", types: ["Dragon", "Flying"] },
      { num: 150, species: "Mewtwo", types: ["Psychic"] },
      { num: 151, species: "Mew", types: ["Psychic"] },
    ],
  },
  {
    title: "Generation 2",
    data: [
      { num: 152, species: "Chikorita", types: ["Grass"] },
      { num: 153, species: "Bayleef", types: ["Grass"] },
      { num: 154, species: "Meganium", types: ["Grass"] },
      { num: 155, species: "Cyndaquil", types: ["Fire"] },
      { num: 156, species: "Quilava", types: ["Fire"] },
      { num: 157, species: "Typhlosion", types: ["Fire"] },
      { num: 158, species: "Totodile", types: ["Water"] },
      { num: 159, species: "Croconaw", types: ["Water"] },
      { num: 160, species: "Feraligatr", types: ["Water"] },
      { num: 161, species: "Sentret", types: ["Normal"] },
      { num: 162, species: "Furret", types: ["Normal"] },
      { num: 163, species: "Hoothoot", types: ["Normal", "Flying"] },
      { num: 164, species: "Noctowl", types: ["Normal", "Flying"] },
      { num: 165, species: "Ledyba", types: ["Bug", "Flying"] },
      { num: 166, species: "Ledian", types: ["Bug", "Flying"] },
      { num: 167, species: "Spinarak", types: ["Bug", "Poison"] },
      { num: 168, species: "Ariados", types: ["Bug", "Poison"] },
      { num: 169, species: "Crobat", types: ["Poison", "Flying"] },
      { num: 170, species: "Chinchou", types: ["Water", "Electric"] },
      { num: 171, species: "Lanturn", types: ["Water", "Electric"] },
      { num: 172, species: "Pichu", types: ["Electric"] },
      { num: 173, species: "Cleffa", types: ["Fairy"] },
      { num: 174, species: "Igglybuff", types: ["Normal", "Fairy"] },
      { num: 175, species: "Togepi", types: ["Fairy"] },
      { num: 176, species: "Togetic", types: ["Fairy", "Flying"] },
      { num: 177, species: "Natu", types: ["Psychic", "Flying"] },
      { num: 178, species: "Xatu", types: ["Psychic", "Flying"] },
      { num: 179, species: "Mareep", types: ["Electric"] },
      { num: 180, species: "Flaaffy", types: ["Electric"] },
      { num: 181, species: "Ampharos", types: ["Electric"] },
      { num: 182, species: "Bellossom", types: ["Grass"] },
      { num: 183, species: "Marill", types: ["Water", "Fairy"] },
      { num: 184, species: "Azumarill", types: ["Water", "Fairy"] },
      { num: 185, species: "Sudowoodo", types: ["Rock"] },
      { num: 186, species: "Politoed", types: ["Water"] },
      { num: 187, species: "Hoppip", types: ["Grass", "Flying"] },
      { num: 188, species: "Skiploom", types: ["Grass", "Flying"] },
      { num: 189, species: "Jumpluff", types: ["Grass", "Flying"] },
      { num: 190, species: "Aipom", types: ["Normal"] },
      { num: 191, species: "Sunkern", types: ["Grass"] },
      { num: 192, species: "Sunflora", types: ["Grass"] },
      { num: 193, species: "Yanma", types: ["Bug", "Flying"] },
      { num: 194, species: "Wooper", types: ["Water", "Ground"] },
      { num: 195, species: "Quagsire", types: ["Water", "Ground"] },
      { num: 196, species: "Espeon", types: ["Psychic"] },
      { num: 197, species: "Umbreon", types: ["Dark"] },
      { num: 198, species: "Murkrow", types: ["Dark", "Flying"] },
      { num: 199, species: "Slowking", types: ["Water", "Psychic"] },
      { num: 200, species: "Misdreavus", types: ["Ghost"] },
      { num: 201, species: "Unown", types: ["Psychic"] },
      { num: 202, species: "Wobbuffet", types: ["Psychic"] },
      { num: 203, species: "Girafarig", types: ["Normal", "Psychic"] },
      { num: 204, species: "Pineco", types: ["Bug"] },
      { num: 205, species: "Forretress", types: ["Bug", "Steel"] },
      { num: 206, species: "Dunsparce", types: ["Normal"] },
      { num: 207, species: "Gligar", types: ["Ground", "Flying"] },
      { num: 208, species: "Steelix", types: ["Steel", "Ground"] },
      { num: 209, species: "Snubbull", types: ["Fairy"] },
      { num: 210, species: "Granbull", types: ["Fairy"] },
      { num: 211, species: "Qwilfish", types: ["Water", "Poison"] },
      { num: 212, species: "Scizor", types: ["Bug", "Steel"] },
      { num: 213, species: "Shuckle", types: ["Bug", "Rock"] },
      { num: 214, species: "Heracross", types: ["Bug", "Fighting"] },
      { num: 215, species: "Sneasel", types: ["Dark", "Ice"] },
      { num: 216, species: "Teddiursa", types: ["Normal"] },
      { num: 217, species: "Ursaring", types: ["Normal"] },
      { num: 218, species: "Slugma", types: ["Fire"] },
      { num: 219, species: "Magcargo", types: ["Fire", "Rock"] },
      { num: 220, species: "Swinub", types: ["Ice", "Ground"] },
      { num: 221, species: "Piloswine", types: ["Ice", "Ground"] },
      { num: 222, species: "Corsola", types: ["Water", "Rock"] },
      { num: 223, species: "Remoraid", types: ["Water"] },
      { num: 224, species: "Octillery", types: ["Water"] },
      { num: 225, species: "Delibird", types: ["Ice", "Flying"] },
      { num: 226, species: "Mantine", types: ["Water", "Flying"] },
      { num: 227, species: "Skarmory", types: ["Steel", "Flying"] },
      { num: 228, species: "Houndour", types: ["Dark", "Fire"] },
      { num: 229, species: "Houndoom", types: ["Dark", "Fire"] },
      { num: 230, species: "Kingdra", types: ["Water", "Dragon"] },
      { num: 231, species: "Phanpy", types: ["Ground"] },
      { num: 232, species: "Donphan", types: ["Ground"] },
      { num: 233, species: "Porygon2", types: ["Normal"] },
      { num: 234, species: "Stantler", types: ["Normal"] },
      { num: 235, species: "Smeargle", types: ["Normal"] },
      { num: 236, species: "Tyrogue", types: ["Fighting"] },
      { num: 237, species: "Hitmontop", types: ["Fighting"] },
      { num: 238, species: "Smoochum", types: ["Ice", "Psychic"] },
      { num: 239, species: "Elekid", types: ["Electric"] },
      { num: 240, species: "Magby", types: ["Fire"] },
      { num: 241, species: "Miltank", types: ["Normal"] },
      { num: 242, species: "Blissey", types: ["Normal"] },
      { num: 243, species: "Raikou", types: ["Electric"] },
      { num: 244, species: "Entei", types: ["Fire"] },
      { num: 245, species: "Suicune", types: ["Water"] },
      { num: 246, species: "Larvitar", types: ["Rock", "Ground"] },
      { num: 247, species: "Pupitar", types: ["Rock", "Ground"] },
      { num: 248, species: "Tyranitar", types: ["Rock", "Dark"] },
      { num: 249, species: "Lugia", types: ["Psychic", "Flying"] },
      { num: 250, species: "Ho-oh", types: ["Fire", "Flying"] },
      { num: 251, species: "Celebi", types: ["Psychic", "Grass"] },
    ],
  },
  {
    title: "Generation 3",
    data: [
      { num: 252, species: "Treecko", types: ["Grass"] },
      { num: 253, species: "Grovyle", types: ["Grass"] },
      { num: 254, species: "Sceptile", types: ["Grass"] },
      { num: 255, species: "Torchic", types: ["Fire"] },
      { num: 256, species: "Combusken", types: ["Fire", "Fighting"] },
      { num: 257, species: "Blaziken", types: ["Fire", "Fighting"] },
      { num: 258, species: "Mudkip", types: ["Water"] },
      { num: 259, species: "Marshtomp", types: ["Water", "Ground"] },
      { num: 260, species: "Swampert", types: ["Water", "Ground"] },
      { num: 261, species: "Poochyena", types: ["Dark"] },
      { num: 262, species: "Mightyena", types: ["Dark"] },
      { num: 263, species: "Zigzagoon", types: ["Normal"] },
      { num: 264, species: "Linoone", types: ["Normal"] },
      { num: 265, species: "Wurmple", types: ["Bug"] },
      { num: 266, species: "Silcoon", types: ["Bug"] },
      { num: 267, species: "Beautifly", types: ["Bug", "Flying"] },
      { num: 268, species: "Cascoon", types: ["Bug"] },
      { num: 269, species: "Dustox", types: ["Bug", "Poison"] },
      { num: 270, species: "Lotad", types: ["Water", "Grass"] },
      { num: 271, species: "Lombre", types: ["Water", "Grass"] },
      { num: 272, species: "Ludicolo", types: ["Water", "Grass"] },
      { num: 273, species: "Seedot", types: ["Grass"] },
      { num: 274, species: "Nuzleaf", types: ["Grass", "Dark"] },
      { num: 275, species: "Shiftry", types: ["Grass", "Dark"] },
      { num: 276, species: "Taillow", types: ["Normal", "Flying"] },
      { num: 277, species: "Swellow", types: ["Normal", "Flying"] },
      { num: 278, species: "Wingull", types: ["Water", "Flying"] },
      { num: 279, species: "Pelipper", types: ["Water", "Flying"] },
      { num: 280, species: "Ralts", types: ["Psychic", "Fairy"] },
      { num: 281, species: "Kirlia", types: ["Psychic", "Fairy"] },
      { num: 282, species: "Gardevoir", types: ["Psychic", "Fairy"] },
      { num: 283, species: "Surskit", types: ["Bug", "Water"] },
      { num: 284, species: "Masquerain", types: ["Bug", "Flying"] },
      { num: 285, species: "Shroomish", types: ["Grass"] },
      { num: 286, species: "Breloom", types: ["Grass", "Fighting"] },
      { num: 287, species: "Slakoth", types: ["Normal"] },
      { num: 288, species: "Vigoroth", types: ["Normal"] },
      { num: 289, species: "Slaking", types: ["Normal"] },
      { num: 290, species: "Nincada", types: ["Bug", "Ground"] },
      { num: 291, species: "Ninjask", types: ["Bug", "Flying"] },
      { num: 292, species: "Shedinja", types: ["Bug", "Ghost"] },
      { num: 293, species: "Whismur", types: ["Normal"] },
      { num: 294, species: "Loudred", types: ["Normal"] },
      { num: 295, species: "Exploud", types: ["Normal"] },
      { num: 296, species: "Makuhita", types: ["Fighting"] },
      { num: 297, species: "Hariyama", types: ["Fighting"] },
      { num: 298, species: "Azurill", types: ["Normal", "Fairy"] },
      { num: 299, species: "Nosepass", types: ["Rock"] },
      { num: 300, species: "Skitty", types: ["Normal"] },
      { num: 301, species: "Delcatty", types: ["Normal"] },
      { num: 302, species: "Sableye", types: ["Dark", "Ghost"] },
      { num: 303, species: "Mawile", types: ["Steel", "Fairy"] },
      { num: 304, species: "Aron", types: ["Steel", "Rock"] },
      { num: 305, species: "Lairon", types: ["Steel", "Rock"] },
      { num: 306, species: "Aggron", types: ["Steel", "Rock"] },
      { num: 307, species: "Meditite", types: ["Fighting", "Psychic"] },
      { num: 308, species: "Medicham", types: ["Fighting", "Psychic"] },
      { num: 309, species: "Electrike", types: ["Electric"] },
      { num: 310, species: "Manectric", types: ["Electric"] },
      { num: 311, species: "Plusle", types: ["Electric"] },
      { num: 312, species: "Minun", types: ["Electric"] },
      { num: 313, species: "Volbeat", types: ["Bug"] },
      { num: 314, species: "Illumise", types: ["Bug"] },
      { num: 315, species: "Roselia", types: ["Grass", "Poison"] },
      { num: 316, species: "Gulpin", types: ["Poison"] },
      { num: 317, species: "Swalot", types: ["Poison"] },
      { num: 318, species: "Carvanha", types: ["Water", "Dark"] },
      { num: 319, species: "Sharpedo", types: ["Water", "Dark"] },
      { num: 320, species: "Wailmer", types: ["Water"] },
      { num: 321, species: "Wailord", types: ["Water"] },
      { num: 322, species: "Numel", types: ["Fire", "Ground"] },
      { num: 323, species: "Camerupt", types: ["Fire", "Ground"] },
      { num: 324, species: "Torkoal", types: ["Fire"] },
      { num: 325, species: "Spoink", types: ["Psychic"] },
      { num: 326, species: "Grumpig", types: ["Psychic"] },
      { num: 327, species: "Spinda", types: ["Normal"] },
      { num: 328, species: "Trapinch", types: ["Ground"] },
      { num: 329, species: "Vibrava", types: ["Ground", "Dragon"] },
      { num: 330, species: "Flygon", types: ["Ground", "Dragon"] },
      { num: 331, species: "Cacnea", types: ["Grass"] },
      { num: 332, species: "Cacturne", types: ["Grass", "Dark"] },
      { num: 333, species: "Swablu", types: ["Normal", "Flying"] },
      { num: 334, species: "Altaria", types: ["Dragon", "Flying"] },
      { num: 335, species: "Zangoose", types: ["Normal"] },
      { num: 336, species: "Seviper", types: ["Poison"] },
      { num: 337, species: "Lunatone", types: ["Rock", "Psychic"] },
      { num: 338, species: "Solrock", types: ["Rock", "Psychic"] },
      { num: 339, species: "Barboach", types: ["Water", "Ground"] },
      { num: 340, species: "Whiscash", types: ["Water", "Ground"] },
      { num: 341, species: "Corphish", types: ["Water"] },
      { num: 342, species: "Crawdaunt", types: ["Water", "Dark"] },
      { num: 343, species: "Baltoy", types: ["Ground", "Psychic"] },
      { num: 344, species: "Claydol", types: ["Ground", "Psychic"] },
      { num: 345, species: "Lileep", types: ["Rock", "Grass"] },
      { num: 346, species: "Cradily", types: ["Rock", "Grass"] },
      { num: 347, species: "Anorith", types: ["Rock", "Bug"] },
      { num: 348, species: "Armaldo", types: ["Rock", "Bug"] },
      { num: 349, species: "Feebas", types: ["Water"] },
      { num: 350, species: "Milotic", types: ["Water"] },
      { num: 351, species: "Castform", types: ["Normal"] },
      { num: 352, species: "Kecleon", types: ["Normal"] },
      { num: 353, species: "Shuppet", types: ["Ghost"] },
      { num: 354, species: "Banette", types: ["Ghost"] },
      { num: 355, species: "Duskull", types: ["Ghost"] },
      { num: 356, species: "Dusclops", types: ["Ghost"] },
      { num: 357, species: "Tropius", types: ["Grass", "Flying"] },
      { num: 358, species: "Chimecho", types: ["Psychic"] },
      { num: 359, species: "Absol", types: ["Dark"] },
      { num: 360, species: "Wynaut", types: ["Psychic"] },
      { num: 361, species: "Snorunt", types: ["Ice"] },
      { num: 362, species: "Glalie", types: ["Ice"] },
      { num: 363, species: "Spheal", types: ["Ice", "Water"] },
      { num: 364, species: "Sealeo", types: ["Ice", "Water"] },
      { num: 365, species: "Walrein", types: ["Ice", "Water"] },
      { num: 366, species: "Clamperl", types: ["Water"] },
      { num: 367, species: "Huntail", types: ["Water"] },
      { num: 368, species: "Gorebyss", types: ["Water"] },
      { num: 369, species: "Relicanth", types: ["Water", "Rock"] },
      { num: 370, species: "Luvdisc", types: ["Water"] },
      { num: 371, species: "Bagon", types: ["Dragon"] },
      { num: 372, species: "Shelgon", types: ["Dragon"] },
      { num: 373, species: "Salamence", types: ["Dragon", "Flying"] },
      { num: 374, species: "Beldum", types: ["Steel", "Psychic"] },
      { num: 375, species: "Metang", types: ["Steel", "Psychic"] },
      { num: 376, species: "Metagross", types: ["Steel", "Psychic"] },
      { num: 377, species: "Regirock", types: ["Rock"] },
      { num: 378, species: "Regice", types: ["Ice"] },
      { num: 379, species: "Registeel", types: ["Steel"] },
      { num: 380, species: "Latias", types: ["Dragon", "Psychic"] },
      { num: 381, species: "Latios", types: ["Dragon", "Psychic"] },
      { num: 382, species: "Kyogre", types: ["Water"] },
      { num: 383, species: "Groudon", types: ["Ground"] },
      { num: 384, species: "Rayquaza", types: ["Dragon", "Flying"] },
      { num: 385, species: "Jirachi", types: ["Steel", "Psychic"] },
      { num: 386, species: "Deoxys", types: ["Psychic"] },
    ],
  },
  {
    title: "Generation 4",
    data: [
      { num: 387, species: "Turtwig", types: ["Grass"] },
      { num: 388, species: "Grotle", types: ["Grass"] },
      { num: 389, species: "Torterra", types: ["Grass", "Ground"] },
      { num: 390, species: "Chimchar", types: ["Fire"] },
      { num: 391, species: "Monferno", types: ["Fire", "Fighting"] },
      { num: 392, species: "Infernape", types: ["Fire", "Fighting"] },
      { num: 393, species: "Piplup", types: ["Water"] },
      { num: 394, species: "Prinplup", types: ["Water"] },
      { num: 395, species: "Empoleon", types: ["Water", "Steel"] },
      { num: 396, species: "Starly", types: ["Normal", "Flying"] },
      { num: 397, species: "Staravia", types: ["Normal", "Flying"] },
      { num: 398, species: "Staraptor", types: ["Normal", "Flying"] },
      { num: 399, species: "Bidoof", types: ["Normal"] },
      { num: 400, species: "Bibarel", types: ["Normal", "Water"] },
      { num: 401, species: "Kricketot", types: ["Bug"] },
      { num: 402, species: "Kricketune", types: ["Bug"] },
      { num: 403, species: "Shinx", types: ["Electric"] },
      { num: 404, species: "Luxio", types: ["Electric"] },
      { num: 405, species: "Luxray", types: ["Electric"] },
      { num: 406, species: "Budew", types: ["Grass", "Poison"] },
      { num: 407, species: "Roserade", types: ["Grass", "Poison"] },
      { num: 408, species: "Cranidos", types: ["Rock"] },
      { num: 409, species: "Rampardos", types: ["Rock"] },
      { num: 410, species: "Shieldon", types: ["Rock", "Steel"] },
      { num: 411, species: "Bastiodon", types: ["Rock", "Steel"] },
      { num: 412, species: "Burmy", types: ["Bug"] },
      { num: 413, species: "Wormadam", types: ["Bug", "Grass"] },
      { num: 414, species: "Mothim", types: ["Bug", "Flying"] },
      { num: 415, species: "Combee", types: ["Bug", "Flying"] },
      { num: 416, species: "Vespiquen", types: ["Bug", "Flying"] },
      { num: 417, species: "Pachirisu", types: ["Electric"] },
      { num: 418, species: "Buizel", types: ["Water"] },
      { num: 419, species: "Floatzel", types: ["Water"] },
      { num: 420, species: "Cherubi", types: ["Grass"] },
      { num: 421, species: "Cherrim", types: ["Grass"] },
      { num: 422, species: "Shellos", types: ["Water"] },
      { num: 423, species: "Gastrodon", types: ["Water", "Ground"] },
      { num: 424, species: "Ambipom", types: ["Normal"] },
      { num: 425, species: "Drifloon", types: ["Ghost", "Flying"] },
      { num: 426, species: "Drifblim", types: ["Ghost", "Flying"] },
      { num: 427, species: "Buneary", types: ["Normal"] },
      { num: 428, species: "Lopunny", types: ["Normal"] },
      { num: 429, species: "Mismagius", types: ["Ghost"] },
      { num: 430, species: "Honchkrow", types: ["Dark", "Flying"] },
      { num: 431, species: "Glameow", types: ["Normal"] },
      { num: 432, species: "Purugly", types: ["Normal"] },
      { num: 433, species: "Chingling", types: ["Psychic"] },
      { num: 434, species: "Stunky", types: ["Poison", "Dark"] },
      { num: 435, species: "Skuntank", types: ["Poison", "Dark"] },
      { num: 436, species: "Bronzor", types: ["Steel", "Psychic"] },
      { num: 437, species: "Bronzong", types: ["Steel", "Psychic"] },
      { num: 438, species: "Bonsly", types: ["Rock"] },
      { num: 439, species: "Mime Jr.", types: ["Psychic", "Fairy"] },
      { num: 440, species: "Happiny", types: ["Normal"] },
      { num: 441, species: "Chatot", types: ["Normal", "Flying"] },
      { num: 442, species: "Spiritomb", types: ["Ghost", "Dark"] },
      { num: 443, species: "Gible", types: ["Dragon", "Ground"] },
      { num: 444, species: "Gabite", types: ["Dragon", "Ground"] },
      { num: 445, species: "Garchomp", types: ["Dragon", "Ground"] },
      { num: 446, species: "Munchlax", types: ["Normal"] },
      { num: 447, species: "Riolu", types: ["Fighting"] },
      { num: 448, species: "Lucario", types: ["Fighting", "Steel"] },
      { num: 449, species: "Hippopotas", types: ["Ground"] },
      { num: 450, species: "Hippowdon", types: ["Ground"] },
      { num: 451, species: "Skorupi", types: ["Poison", "Bug"] },
      { num: 452, species: "Drapion", types: ["Poison", "Dark"] },
      { num: 453, species: "Croagunk", types: ["Poison", "Fighting"] },
      { num: 454, species: "Toxicroak", types: ["Poison", "Fighting"] },
      { num: 455, species: "Carnivine", types: ["Grass"] },
      { num: 456, species: "Finneon", types: ["Water"] },
      { num: 457, species: "Lumineon", types: ["Water"] },
      { num: 458, species: "Mantyke", types: ["Water", "Flying"] },
      { num: 459, species: "Snover", types: ["Grass", "Ice"] },
      { num: 460, species: "Abomasnow", types: ["Grass", "Ice"] },
      { num: 461, species: "Weavile", types: ["Dark", "Ice"] },
      { num: 462, species: "Magnezone", types: ["Electric", "Steel"] },
      { num: 463, species: "Lickilicky", types: ["Normal"] },
      { num: 464, species: "Rhyperior", types: ["Ground", "Rock"] },
      { num: 465, species: "Tangrowth", types: ["Grass"] },
      { num: 466, species: "Electivire", types: ["Electric"] },
      { num: 467, species: "Magmortar", types: ["Fire"] },
      { num: 468, species: "Togekiss", types: ["Fairy", "Flying"] },
      { num: 469, species: "Yanmega", types: ["Bug", "Flying"] },
      { num: 470, species: "Leafeon", types: ["Grass"] },
      { num: 471, species: "Glaceon", types: ["Ice"] },
      { num: 472, species: "Gliscor", types: ["Ground", "Flying"] },
      { num: 473, species: "Mamoswine", types: ["Ice", "Ground"] },
      { num: 474, species: "Porygon-Z", types: ["Normal"] },
      { num: 475, species: "Gallade", types: ["Psychic", "Fighting"] },
      { num: 476, species: "Probopass", types: ["Rock", "Steel"] },
      { num: 477, species: "Dusknoir", types: ["Ghost"] },
      { num: 478, species: "Froslass", types: ["Ice", "Ghost"] },
      { num: 479, species: "Rotom", types: ["Electric", "Ghost"] },
      { num: 480, species: "Uxie", types: ["Psychic"] },
      { num: 481, species: "Mesprit", types: ["Psychic"] },
      { num: 482, species: "Azelf", types: ["Psychic"] },
      { num: 483, species: "Dialga", types: ["Steel", "Dragon"] },
      { num: 484, species: "Palkia", types: ["Water", "Dragon"] },
      { num: 485, species: "Heatran", types: ["Fire", "Steel"] },
      { num: 486, species: "Regigigas", types: ["Normal"] },
      { num: 487, species: "Giratina", types: ["Ghost", "Dragon"] },
      { num: 488, species: "Cresselia", types: ["Psychic"] },
      { num: 489, species: "Phione", types: ["Water"] },
      { num: 490, species: "Manaphy", types: ["Water"] },
      { num: 491, species: "Darkrai", types: ["Dark"] },
      { num: 492, species: "Shaymin", types: ["Grass"] },
      { num: 493, species: "Arceus", types: ["Normal"] },
    ],
  },
  {
    title: "Generation 5",
    data: [
      { num: 494, species: "Victini", types: ["Psychic", "Fire"] },
      { num: 495, species: "Snivy", types: ["Grass"] },
      { num: 496, species: "Servine", types: ["Grass"] },
      { num: 497, species: "Serperior", types: ["Grass"] },
      { num: 498, species: "Tepig", types: ["Fire"] },
      { num: 499, species: "Pignite", types: ["Fire", "Fighting"] },
      { num: 500, species: "Emboar", types: ["Fire", "Fighting"] },
      { num: 501, species: "Oshawott", types: ["Water"] },
      { num: 502, species: "Dewott", types: ["Water"] },
      { num: 503, species: "Samurott", types: ["Water"] },
      { num: 504, species: "Patrat", types: ["Normal"] },
      { num: 505, species: "Watchog", types: ["Normal"] },
      { num: 506, species: "Lillipup", types: ["Normal"] },
      { num: 507, species: "Herdier", types: ["Normal"] },
      { num: 508, species: "Stoutland", types: ["Normal"] },
      { num: 509, species: "Purrloin", types: ["Dark"] },
      { num: 510, species: "Liepard", types: ["Dark"] },
      { num: 511, species: "Pansage", types: ["Grass"] },
      { num: 512, species: "Simisage", types: ["Grass"] },
      { num: 513, species: "Pansear", types: ["Fire"] },
      { num: 514, species: "Simisear", types: ["Fire"] },
      { num: 515, species: "Panpour", types: ["Water"] },
      { num: 516, species: "Simipour", types: ["Water"] },
      { num: 517, species: "Munna", types: ["Psychic"] },
      { num: 518, species: "Musharna", types: ["Psychic"] },
      { num: 519, species: "Pidove", types: ["Normal", "Flying"] },
      { num: 520, species: "Tranquill", types: ["Normal", "Flying"] },
      { num: 521, species: "Unfezant", types: ["Normal", "Flying"] },
      { num: 522, species: "Blitzle", types: ["Electric"] },
      { num: 523, species: "Zebstrika", types: ["Electric"] },
      { num: 524, species: "Roggenrola", types: ["Rock"] },
      { num: 525, species: "Boldore", types: ["Rock"] },
      { num: 526, species: "Gigalith", types: ["Rock"] },
      { num: 527, species: "Woobat", types: ["Psychic", "Flying"] },
      { num: 528, species: "Swoobat", types: ["Psychic", "Flying"] },
      { num: 529, species: "Drilbur", types: ["Ground"] },
      { num: 530, species: "Excadrill", types: ["Ground", "Steel"] },
      { num: 531, species: "Audino", types: ["Normal"] },
      { num: 532, species: "Timburr", types: ["Fighting"] },
      { num: 533, species: "Gurdurr", types: ["Fighting"] },
      { num: 534, species: "Conkeldurr", types: ["Fighting"] },
      { num: 535, species: "Tympole", types: ["Water"] },
      { num: 536, species: "Palpitoad", types: ["Water", "Ground"] },
      { num: 537, species: "Seismitoad", types: ["Water", "Ground"] },
      { num: 538, species: "Throh", types: ["Fighting"] },
      { num: 539, species: "Sawk", types: ["Fighting"] },
      { num: 540, species: "Sewaddle", types: ["Bug", "Grass"] },
      { num: 541, species: "Swadloon", types: ["Bug", "Grass"] },
      { num: 542, species: "Leavanny", types: ["Bug", "Grass"] },
      { num: 543, species: "Venipede", types: ["Bug", "Poison"] },
      { num: 544, species: "Whirlipede", types: ["Bug", "Poison"] },
      { num: 545, species: "Scolipede", types: ["Bug", "Poison"] },
      { num: 546, species: "Cottonee", types: ["Grass", "Fairy"] },
      { num: 547, species: "Whimsicott", types: ["Grass", "Fairy"] },
      { num: 548, species: "Petilil", types: ["Grass"] },
      { num: 549, species: "Lilligant", types: ["Grass"] },
      { num: 550, species: "Basculin", types: ["Water"] },
      { num: 551, species: "Sandile", types: ["Ground", "Dark"] },
      { num: 552, species: "Krokorok", types: ["Ground", "Dark"] },
      { num: 553, species: "Krookodile", types: ["Ground", "Dark"] },
      { num: 554, species: "Darumaka", types: ["Fire"] },
      { num: 555, species: "Darmanitan", types: ["Fire"] },
      { num: 556, species: "Maractus", types: ["Grass"] },
      { num: 557, species: "Dwebble", types: ["Bug", "Rock"] },
      { num: 558, species: "Crustle", types: ["Bug", "Rock"] },
      { num: 559, species: "Scraggy", types: ["Dark", "Fighting"] },
      { num: 560, species: "Scrafty", types: ["Dark", "Fighting"] },
      { num: 561, species: "Sigilyph", types: ["Psychic", "Flying"] },
      { num: 562, species: "Yamask", types: ["Ghost"] },
      { num: 563, species: "Cofagrigus", types: ["Ghost"] },
      { num: 564, species: "Tirtouga", types: ["Water", "Rock"] },
      { num: 565, species: "Carracosta", types: ["Water", "Rock"] },
      { num: 566, species: "Archen", types: ["Rock", "Flying"] },
      { num: 567, species: "Archeops", types: ["Rock", "Flying"] },
      { num: 568, species: "Trubbish", types: ["Poison"] },
      { num: 569, species: "Garbodor", types: ["Poison"] },
      { num: 570, species: "Zorua", types: ["Dark"] },
      { num: 571, species: "Zoroark", types: ["Dark"] },
      { num: 572, species: "Minccino", types: ["Normal"] },
      { num: 573, species: "Cinccino", types: ["Normal"] },
      { num: 574, species: "Gothita", types: ["Psychic"] },
      { num: 575, species: "Gothorita", types: ["Psychic"] },
      { num: 576, species: "Gothitelle", types: ["Psychic"] },
      { num: 577, species: "Solosis", types: ["Psychic"] },
      { num: 578, species: "Duosion", types: ["Psychic"] },
      { num: 579, species: "Reuniclus", types: ["Psychic"] },
      { num: 580, species: "Ducklett", types: ["Water", "Flying"] },
      { num: 581, species: "Swanna", types: ["Water", "Flying"] },
      { num: 582, species: "Vanillite", types: ["Ice"] },
      { num: 583, species: "Vanillish", types: ["Ice"] },
      { num: 584, species: "Vanilluxe", types: ["Ice"] },
      { num: 585, species: "Deerling", types: ["Normal", "Grass"] },
      { num: 586, species: "Sawsbuck", types: ["Normal", "Grass"] },
      { num: 587, species: "Emolga", types: ["Electric", "Flying"] },
      { num: 588, species: "Karrablast", types: ["Bug"] },
      { num: 589, species: "Escavalier", types: ["Bug", "Steel"] },
      { num: 590, species: "Foongus", types: ["Grass", "Poison"] },
      { num: 591, species: "Amoonguss", types: ["Grass", "Poison"] },
      { num: 592, species: "Frillish", types: ["Water", "Ghost"] },
      { num: 593, species: "Jellicent", types: ["Water", "Ghost"] },
      { num: 594, species: "Alomomola", types: ["Water"] },
      { num: 595, species: "Joltik", types: ["Bug", "Electric"] },
      { num: 596, species: "Galvantula", types: ["Bug", "Electric"] },
      { num: 597, species: "Ferroseed", types: ["Grass", "Steel"] },
      { num: 598, species: "Ferrothorn", types: ["Grass", "Steel"] },
      { num: 599, species: "Klink", types: ["Steel"] },
      { num: 600, species: "Klang", types: ["Steel"] },
      { num: 601, species: "Klinklang", types: ["Steel"] },
      { num: 602, species: "Tynamo", types: ["Electric"] },
      { num: 603, species: "Eelektrik", types: ["Electric"] },
      { num: 604, species: "Eelektross", types: ["Electric"] },
      { num: 605, species: "Elgyem", types: ["Psychic"] },
      { num: 606, species: "Beheeyem", types: ["Psychic"] },
      { num: 607, species: "Litwick", types: ["Ghost", "Fire"] },
      { num: 608, species: "Lampent", types: ["Ghost", "Fire"] },
      { num: 609, species: "Chandelure", types: ["Ghost", "Fire"] },
      { num: 610, species: "Axew", types: ["Dragon"] },
      { num: 611, species: "Fraxure", types: ["Dragon"] },
      { num: 612, species: "Haxorus", types: ["Dragon"] },
      { num: 613, species: "Cubchoo", types: ["Ice"] },
      { num: 614, species: "Beartic", types: ["Ice"] },
      { num: 615, species: "Cryogonal", types: ["Ice"] },
      { num: 616, species: "Shelmet", types: ["Bug"] },
      { num: 617, species: "Accelgor", types: ["Bug"] },
      { num: 618, species: "Stunfisk", types: ["Ground", "Electric"] },
      { num: 619, species: "Mienfoo", types: ["Fighting"] },
      { num: 620, species: "Mienshao", types: ["Fighting"] },
      { num: 621, species: "Druddigon", types: ["Dragon"] },
      { num: 622, species: "Golett", types: ["Ground", "Ghost"] },
      { num: 623, species: "Golurk", types: ["Ground", "Ghost"] },
      { num: 624, species: "Pawniard", types: ["Dark", "Steel"] },
      { num: 625, species: "Bisharp", types: ["Dark", "Steel"] },
      { num: 626, species: "Bouffalant", types: ["Normal"] },
      { num: 627, species: "Rufflet", types: ["Normal", "Flying"] },
      { num: 628, species: "Braviary", types: ["Normal", "Flying"] },
      { num: 629, species: "Vullaby", types: ["Dark", "Flying"] },
      { num: 630, species: "Mandibuzz", types: ["Dark", "Flying"] },
      { num: 631, species: "Heatmor", types: ["Fire"] },
      { num: 632, species: "Durant", types: ["Bug", "Steel"] },
      { num: 633, species: "Deino", types: ["Dark", "Dragon"] },
      { num: 634, species: "Zweilous", types: ["Dark", "Dragon"] },
      { num: 635, species: "Hydreigon", types: ["Dark", "Dragon"] },
      { num: 636, species: "Larvesta", types: ["Bug", "Fire"] },
      { num: 637, species: "Volcarona", types: ["Bug", "Fire"] },
      { num: 638, species: "Cobalion", types: ["Steel", "Fighting"] },
      { num: 639, species: "Terrakion", types: ["Rock", "Fighting"] },
      { num: 640, species: "Virizion", types: ["Grass", "Fighting"] },
      { num: 641, species: "Tornadus", types: ["Flying"] },
      { num: 642, species: "Thundurus", types: ["Electric", "Flying"] },
      { num: 643, species: "Reshiram", types: ["Dragon", "Fire"] },
      { num: 644, species: "Zekrom", types: ["Dragon", "Electric"] },
      { num: 645, species: "Landorus", types: ["Ground", "Flying"] },
      { num: 646, species: "Kyurem", types: ["Dragon", "Ice"] },
      { num: 647, species: "Keldeo", types: ["Water", "Fighting"] },
      { num: 648, species: "Meloetta", types: ["Normal", "Psychic"] },
      { num: 649, species: "Genesect", types: ["Bug", "Steel"] },
    ],
  },
  {
    title: "Generation 6",
    data: [
      { num: 650, species: "Chespin", types: ["Grass"] },
      { num: 651, species: "Quilladin", types: ["Grass"] },
      { num: 652, species: "Chesnaught", types: ["Grass", "Fighting"] },
      { num: 653, species: "Fennekin", types: ["Fire"] },
      { num: 654, species: "Braixen", types: ["Fire"] },
      { num: 655, species: "Delphox", types: ["Fire", "Psychic"] },
      { num: 656, species: "Froakie", types: ["Water"] },
      { num: 657, species: "Frogadier", types: ["Water"] },
      { num: 658, species: "Greninja", types: ["Water", "Dark"] },
      { num: 659, species: "Bunnelby", types: ["Normal"] },
      { num: 660, species: "Diggersby", types: ["Normal", "Ground"] },
      { num: 661, species: "Fletchling", types: ["Normal", "Flying"] },
      { num: 662, species: "Fletchinder", types: ["Fire", "Flying"] },
      { num: 663, species: "Talonflame", types: ["Fire", "Flying"] },
      { num: 664, species: "Scatterbug", types: ["Bug"] },
      { num: 665, species: "Spewpa", types: ["Bug"] },
      { num: 666, species: "Vivillon", types: ["Bug", "Flying"] },
      { num: 667, species: "Litleo", types: ["Fire", "Normal"] },
      { num: 668, species: "Pyroar", types: ["Fire", "Normal"] },
      { num: 669, species: "Flabébé", types: ["Fairy"] },
      { num: 670, species: "Floette", types: ["Fairy"] },
      { num: 671, species: "Florges", types: ["Fairy"] },
      { num: 672, species: "Skiddo", types: ["Grass"] },
      { num: 673, species: "Gogoat", types: ["Grass"] },
      { num: 674, species: "Pancham", types: ["Fighting"] },
      { num: 675, species: "Pangoro", types: ["Fighting", "Dark"] },
      { num: 676, species: "Furfrou", types: ["Normal"] },
      { num: 677, species: "Espurr", types: ["Psychic"] },
      { num: 678, species: "Meowstic", types: ["Psychic"] },
      { num: 679, species: "Honedge", types: ["Steel", "Ghost"] },
      { num: 680, species: "Doublade", types: ["Steel", "Ghost"] },
      { num: 681, species: "Aegislash", types: ["Steel", "Ghost"] },
      { num: 682, species: "Spritzee", types: ["Fairy"] },
      { num: 683, species: "Aromatisse", types: ["Fairy"] },
      { num: 684, species: "Swirlix", types: ["Fairy"] },
      { num: 685, species: "Slurpuff", types: ["Fairy"] },
      { num: 686, species: "Inkay", types: ["Dark", "Psychic"] },
      { num: 687, species: "Malamar", types: ["Dark", "Psychic"] },
      { num: 688, species: "Binacle", types: ["Rock", "Water"] },
      { num: 689, species: "Barbaracle", types: ["Rock", "Water"] },
      { num: 690, species: "Skrelp", types: ["Poison", "Water"] },
      { num: 691, species: "Dragalge", types: ["Poison", "Dragon"] },
      { num: 692, species: "Clauncher", types: ["Water"] },
      { num: 693, species: "Clawitzer", types: ["Water"] },
      { num: 694, species: "Helioptile", types: ["Electric", "Normal"] },
      { num: 695, species: "Heliolisk", types: ["Electric", "Normal"] },
      { num: 696, species: "Tyrunt", types: ["Rock", "Dragon"] },
      { num: 697, species: "Tyrantrum", types: ["Rock", "Dragon"] },
      { num: 698, species: "Amaura", types: ["Rock", "Ice"] },
      { num: 699, species: "Aurorus", types: ["Rock", "Ice"] },
      { num: 700, species: "Sylveon", types: ["Fairy"] },
      { num: 701, species: "Hawlucha", types: ["Fighting", "Flying"] },
      { num: 702, species: "Dedenne", types: ["Electric", "Fairy"] },
      { num: 703, species: "Carbink", types: ["Rock", "Fairy"] },
      { num: 704, species: "Goomy", types: ["Dragon"] },
      { num: 705, species: "Sliggoo", types: ["Dragon"] },
      { num: 706, species: "Goodra", types: ["Dragon"] },
      { num: 707, species: "Klefki", types: ["Steel", "Fairy"] },
      { num: 708, species: "Phantump", types: ["Ghost", "Grass"] },
      { num: 709, species: "Trevenant", types: ["Ghost", "Grass"] },
      { num: 710, species: "Pumpkaboo", types: ["Ghost", "Grass"] },
      { num: 711, species: "Gourgeist", types: ["Ghost", "Grass"] },
      { num: 712, species: "Bergmite", types: ["Ice"] },
      { num: 713, species: "Avalugg", types: ["Ice"] },
      { num: 714, species: "Noibat", types: ["Flying", "Dragon"] },
      { num: 715, species: "Noivern", types: ["Flying", "Dragon"] },
      { num: 716, species: "Xerneas", types: ["Fairy"] },
      { num: 717, species: "Yveltal", types: ["Dark", "Flying"] },
      { num: 718, species: "Zygarde", types: ["Dragon", "Ground"] },
      { num: 719, species: "Diancie", types: ["Rock", "Fairy"] },
      { num: 720, species: "Hoopa", types: ["Psychic", "Ghost"] },
      { num: 721, species: "Volcanion", types: ["Fire", "Water"] },
    ],
  },
  {
    title: "Generation 7",
    data: [
      { num: 722, species: "Rowlet", types: ["Grass", "Flying"] },
      { num: 723, species: "Dartrix", types: ["Grass", "Flying"] },
      { num: 724, species: "Decidueye", types: ["Grass", "Ghost"] },
      { num: 725, species: "Litten", types: ["Fire"] },
      { num: 726, species: "Torracat", types: ["Fire"] },
      { num: 727, species: "Incineroar", types: ["Fire", "Dark"] },
      { num: 728, species: "Popplio", types: ["Water"] },
      { num: 729, species: "Brionne", types: ["Water"] },
      { num: 730, species: "Primarina", types: ["Water", "Fairy"] },
      { num: 731, species: "Pikipek", types: ["Normal", "Flying"] },
      { num: 732, species: "Trumbeak", types: ["Normal", "Flying"] },
      { num: 733, species: "Toucannon", types: ["Normal", "Flying"] },
      { num: 734, species: "Yungoos", types: ["Normal"] },
      { num: 735, species: "Gumshoos", types: ["Normal"] },
      { num: 736, species: "Grubbin", types: ["Bug"] },
      { num: 737, species: "Charjabug", types: ["Bug", "Electric"] },
      { num: 738, species: "Vikavolt", types: ["Bug", "Electric"] },
      { num: 739, species: "Crabrawler", types: ["Fighting"] },
      { num: 740, species: "Crabominable", types: ["Fighting", "Ice"] },
      { num: 741, species: "Oricorio", types: ["Fire", "Flying"] },
      { num: 742, species: "Cutiefly", types: ["Bug", "Fairy"] },
      { num: 743, species: "Ribombee", types: ["Bug", "Fairy"] },
      { num: 744, species: "Rockruff", types: ["Rock"] },
      { num: 745, species: "Lycanroc", types: ["Rock"] },
      { num: 746, species: "Wishiwashi", types: ["Water"] },
      { num: 747, species: "Mareanie", types: ["Poison", "Water"] },
      { num: 748, species: "Toxapex", types: ["Poison", "Water"] },
      { num: 749, species: "Mudbray", types: ["Ground"] },
      { num: 750, species: "Mudsdale", types: ["Ground"] },
      { num: 751, species: "Dewpider", types: ["Water", "Bug"] },
      { num: 752, species: "Araquanid", types: ["Water", "Bug"] },
      { num: 753, species: "Fomantis", types: ["Grass"] },
      { num: 754, species: "Lurantis", types: ["Grass"] },
      { num: 755, species: "Morelull", types: ["Grass", "Fairy"] },
      { num: 756, species: "Shiinotic", types: ["Grass", "Fairy"] },
      { num: 757, species: "Salandit", types: ["Poison", "Fire"] },
      { num: 758, species: "Salazzle", types: ["Poison", "Fire"] },
      { num: 759, species: "Stufful", types: ["Normal", "Fighting"] },
      { num: 760, species: "Bewear", types: ["Normal", "Fighting"] },
      { num: 761, species: "Bounsweet", types: ["Grass"] },
      { num: 762, species: "Steenee", types: ["Grass"] },
      { num: 763, species: "Tsareena", types: ["Grass"] },
      { num: 764, species: "Comfey", types: ["Fairy"] },
      { num: 765, species: "Oranguru", types: ["Normal", "Psychic"] },
      { num: 766, species: "Passimian", types: ["Fighting"] },
      { num: 767, species: "Wimpod", types: ["Bug", "Water"] },
      { num: 768, species: "Golisopod", types: ["Bug", "Water"] },
      { num: 769, species: "Sandygast", types: ["Ghost", "Ground"] },
      { num: 770, species: "Palossand", types: ["Ghost", "Ground"] },
      { num: 771, species: "Pyukumuku", types: ["Water"] },
      { num: 772, species: "Type: Null", types: ["Normal"] },
      { num: 773, species: "Silvally", types: ["Normal"] },
      { num: 774, species: "Minior", types: ["Rock", "Flying"] },
      { num: 775, species: "Komala", types: ["Normal"] },
      { num: 776, species: "Turtonator", types: ["Fire", "Dragon"] },
      { num: 777, species: "Togedemaru", types: ["Electric", "Steel"] },
      { num: 778, species: "Mimikyu", types: ["Ghost", "Fairy"] },
      { num: 779, species: "Bruxish", types: ["Water", "Psychic"] },
      { num: 780, species: "Drampa", types: ["Normal", "Dragon"] },
      { num: 781, species: "Dhelmise", types: ["Ghost", "Grass"] },
      { num: 782, species: "Jangmo-o", types: ["Dragon"] },
      { num: 783, species: "Hakamo-o", types: ["Dragon", "Fighting"] },
      { num: 784, species: "Kommo-o", types: ["Dragon", "Fighting"] },
      { num: 785, species: "Tapu Koko", types: ["Electric", "Fairy"] },
      { num: 786, species: "Tapu Lele", types: ["Psychic", "Fairy"] },
      { num: 787, species: "Tapu Bulu", types: ["Grass", "Fairy"] },
      { num: 788, species: "Tapu Fini", types: ["Water", "Fairy"] },
      { num: 789, species: "Cosmog", types: ["Psychic"] },
      { num: 790, species: "Cosmoem", types: ["Psychic"] },
      { num: 791, species: "Solgaleo", types: ["Psychic", "Steel"] },
      { num: 792, species: "Lunala", types: ["Psychic", "Ghost"] },
      { num: 793, species: "Nihilego", types: ["Rock", "Poison"] },
      { num: 794, species: "Buzzwole", types: ["Bug", "Fighting"] },
      { num: 795, species: "Pheromosa", types: ["Bug", "Fighting"] },
      { num: 796, species: "Xurkitree", types: ["Electric"] },
      { num: 797, species: "Celesteela", types: ["Steel", "Flying"] },
      { num: 798, species: "Kartana", types: ["Grass", "Steel"] },
      { num: 799, species: "Guzzlord", types: ["Dark", "Dragon"] },
      { num: 800, species: "Necrozma", types: ["Psychic"] },
      { num: 801, species: "Magearna", types: ["Steel", "Fairy"] },
      { num: 802, species: "Marshadow", types: ["Fighting", "Ghost"] },
      { num: 803, species: "Poipole", types: ["Poison"] },
      { num: 804, species: "Naganadel", types: ["Poison", "Dragon"] },
      { num: 805, species: "Stakataka", types: ["Rock", "Steel"] },
      { num: 806, species: "Blacephalon", types: ["Fire", "Ghost"] },
      { num: 807, species: "Zeraora", types: ["Electric"] },
      { num: 808, species: "Meltan", types: ["Steel"] },
      { num: 809, species: "Melmetal", types: ["Steel"] },
    ],
  },
  {
    title: "Generation 8",
    data: [
      { num: 810, species: "Grookey", types: ["Grass"] },
      { num: 811, species: "Thwackey", types: ["Grass"] },
      { num: 812, species: "Rillaboom", types: ["Grass"] },
      { num: 813, species: "Scorbunny", types: ["Fire"] },
      { num: 814, species: "Raboot", types: ["Fire"] },
      { num: 815, species: "Cinderace", types: ["Fire"] },
      { num: 816, species: "Sobble", types: ["Water"] },
      { num: 817, species: "Drizzile", types: ["Water"] },
      { num: 818, species: "Inteleon", types: ["Water"] },
      { num: 819, species: "Skwovet", types: ["Normal"] },
      { num: 820, species: "Greedent", types: ["Normal"] },
      { num: 821, species: "Rookidee", types: ["Flying"] },
      { num: 822, species: "Corvisquire", types: ["Flying"] },
      { num: 823, species: "Corviknight", types: ["Flying", "Steel"] },
      { num: 824, species: "Blipbug", types: ["Bug"] },
      { num: 825, species: "Dottler", types: ["Bug", "Psychic"] },
      { num: 826, species: "Orbeetle", types: ["Bug", "Psychic"] },
      { num: 827, species: "Nickit", types: ["Dark"] },
      { num: 828, species: "Thievul", types: ["Dark"] },
      { num: 829, species: "Gossifleur", types: ["Grass"] },
      { num: 830, species: "Eldegoss", types: ["Grass"] },
      { num: 831, species: "Wooloo", types: ["Normal"] },
      { num: 832, species: "Dubwool", types: ["Normal"] },
      { num: 833, species: "Chewtle", types: ["Water"] },
      { num: 834, species: "Drednaw", types: ["Water", "Rock"] },
      { num: 835, species: "Yamper", types: ["Electric"] },
      { num: 836, species: "Boltund", types: ["Electric"] },
      { num: 837, species: "Rolycoly", types: ["Rock"] },
      { num: 838, species: "Carkol", types: ["Rock", "Fire"] },
      { num: 839, species: "Coalossal", types: ["Rock", "Fire"] },
      { num: 840, species: "Applin", types: ["Grass", "Dragon"] },
      { num: 841, species: "Flapple", types: ["Grass", "Dragon"] },
      { num: 842, species: "Appletun", types: ["Grass", "Dragon"] },
      { num: 843, species: "Silicobra", types: ["Ground"] },
      { num: 844, species: "Sandaconda", types: ["Ground"] },
      { num: 845, species: "Cramorant", types: ["Flying", "Water"] },
      { num: 846, species: "Arrokuda", types: ["Water"] },
      { num: 847, species: "Barraskewda", types: ["Water"] },
      { num: 848, species: "Toxel", types: ["Electric", "Poison"] },
      { num: 849, species: "Toxtricity", types: ["Electric", "Poison"] },
      { num: 850, species: "Sizzlipede", types: ["Fire", "Bug"] },
      { num: 851, species: "Centiskorch", types: ["Fire", "Bug"] },
      { num: 852, species: "Clobbopus", types: ["Fighting"] },
      { num: 853, species: "Grapploct", types: ["Fighting"] },
      { num: 854, species: "Sinistea", types: ["Ghost"] },
      { num: 855, species: "Polteageist", types: ["Ghost"] },
      { num: 856, species: "Hatenna", types: ["Psychic"] },
      { num: 857, species: "Hattrem", types: ["Psychic"] },
      { num: 858, species: "Hatterene", types: ["Psychic", "Fairy"] },
      { num: 859, species: "Impidimp", types: ["Dark", "Fairy"] },
      { num: 860, species: "Morgrem", types: ["Dark", "Fairy"] },
      { num: 861, species: "Grimmsnarl", types: ["Dark", "Fairy"] },
      { num: 862, species: "Obstagoon", types: ["Dark", "Normal"] },
      { num: 863, species: "Perrserker", types: ["Steel"] },
      { num: 864, species: "Cursola", types: ["Ghost"] },
      { num: 865, species: "Sirfetch'd", types: ["Fighting"] },
      { num: 866, species: "Mr. Rime", types: ["Ice", "Psychic"] },
      { num: 867, species: "Runerigus", types: ["Ground", "Ghost"] },
      { num: 868, species: "Milcery", types: ["Fairy"] },
      { num: 869, species: "Alcremie", types: ["Fairy"] },
      { num: 870, species: "Falinks", types: ["Fighting"] },
      { num: 871, species: "Pincurchin", types: ["Electric"] },
      { num: 872, species: "Snom", types: ["Ice", "Bug"] },
      { num: 873, species: "Frosmoth", types: ["Ice", "Bug"] },
      { num: 874, species: "Stonjourner", types: ["Rock"] },
      { num: 875, species: "Eiscue", types: ["Ice"] },
      { num: 876, species: "Indeedee", types: ["Psychic", "Normal"] },
      { num: 877, species: "Morpeko", types: ["Electric", "Dark"] },
      { num: 878, species: "Cufant", types: ["Steel"] },
      { num: 879, species: "Copperajah", types: ["Steel"] },
      { num: 880, species: "Dracozolt", types: ["Electric", "Dragon"] },
      { num: 881, species: "Arctozolt", types: ["Electric", "Ice"] },
      { num: 882, species: "Dracovish", types: ["Water", "Dragon"] },
      { num: 883, species: "Arctovish", types: ["Water", "Ice"] },
      { num: 884, species: "Duraludon", types: ["Steel", "Dragon"] },
      { num: 885, species: "Dreepy", types: ["Dragon", "Ghost"] },
      { num: 886, species: "Drakloak", types: ["Dragon", "Ghost"] },
      { num: 887, species: "Dragapult", types: ["Dragon", "Ghost"] },
      { num: 888, species: "Zacian", types: ["Fairy", "Steel"] },
      { num: 889, species: "Zamazenta", types: ["Fighting", "Steel"] },
      { num: 890, species: "Eternatus", types: ["Poison", "Dragon"] },
      { num: 891, species: "Kubfu", types: ["Fighting"] },
      { num: 892, species: "Urshifu", types: ["Fighting", "Dark"] },
      { num: 893, species: "Zarude", types: ["Dark", "Grass"] },
      { num: 894, species: "Regieleki", types: ["Electric"] },
      { num: 895, species: "Regidrago", types: ["Dragon"] },
      { num: 896, species: "Glastrier", types: ["Ice"] },
      { num: 897, species: "Spectrier", types: ["Ghost"] },
      { num: 898, species: "Calyrex", types: ["Psychic", "Grass"] },
    ],
  },
];
